# Use the official Ubuntu base image
FROM ubuntu:latest

# Proxy environment variables
ENV http_proxy=http://proxy.mycompany.com:8080 \
    https_proxy=http://proxy.mycompany.com:9443 \
    no_proxy=127.0.0.1,localhost,docker.internal,.svc,.cluster.local,\
10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.100.192.1 \
    NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

# Set noninteractive mode for apt to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Copy the UC4 functions script to the image, and set the file owner, group, & mode.
COPY --chmod=0755 --chown=1000:1000 uc4_functions_k8s_public.sh /home/ubuntu

# Add utilities and certificates
USER root
RUN apt-get update && apt-get -y install p11-kit bash telnet iputils-ping \
iproute2 traceroute net-tools dnsutils gawk curl wget vim less ripgrep && \
  wget -qP /usr/local/bin https://dl.k8s.io/release/$(wget -qO- https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && \
  chmod +x /usr/local/bin/kubectl && \
  echo "source /home/ubuntu/uc4_functions_k8s_public.sh" >> /home/ubuntu/.bashrc && \
  ln -s /usr/server/tmp/log /log && ln -s /usr/server/tmp/trace /trc && \
  ln -sf /usr/bin/bash /bin/sh

# Switch to non-root user (1000 corresponds to the 'ubuntu' user & group in the ubuntu image.)
USER 1000:1000

# Start an interactive shell
ENTRYPOINT ["/usr/bin/bash", "--rcfile", "/home/ubuntu/.bashrc", "-c", "tail -f /dev/null"]